export const colors = {
  textPrimary: '#2D3142',
  textSecondary: '#9B93AB',
  textMuted: '#C4A898',
  accentOrange: '#FF9E20',
  accentHighlight: '#FFB85C',
  accentPurple: '#D4A8E8',
  domainSelectedBg: '#FFF0E0',
  buttonGradientStart: '#FF9E20',
  buttonGradientEnd: '#E0C8F0',
  loginButtonBg: '#FFF8F0',
  inputLine: '#F5DCC8',
  signupButton: '#FFC680',
  footerText: '#A0A0A0',
  linkOrange: '#FF9E20',
} as const;
